### ISSUE TITLE
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.

### ISSUE THREAD

**Issue by sanzinken** [geoffthibeau/simple-drag-drop-text#25] opened 2017-01-19 19:48 UTC
atom-text-editor.Object.defineProperty.get - /opt/atom/resources/app.asar/src/text-editor-element.js:68:18
<unknown> - /home/l3xx/.atom/packages/simple-drag-drop-text/lib/simple-drag-drop-text.coffee:58:26
_combinedTickCallback - internal/process/next_tick.js:67:7
process._tickCallback - internal/process/next_tick.js:98:9

**Comment by ghost** [comment] 2017-01-22 11:15
Duplicate of #23

**Closed as completed** 2017-02-09 14:58 UTC
